// This file is AUTOGENERATED by appMobi SDK
// The values in accelArray are sent to the SDK
// by the dev.accelcapture development application

accelStep = 0;
accelDelay = 100;
accelArray = [
				{x:0.2,y:-0.5,z:0.2},
				{x:0.2,y:0.5,z:0.2},
				{x:-0.2,y:0.0,z:0.2},
				{x:-0.2,y:0.0,z:-0.2},
				{x:0.2,y:-0.5,z:0.2},
				{x:0.2,y:0.5,z:0.2},
			 ];

function accelReplay()
{
	accelStep = 0;
    if( accelStep < accelArray.length )
    	setTimeout(doAccelStep,0);
}

function doAccelStep()
{
	var acc = accelArray[accelStep];
	frm.contentWindow.AppMobi._accel = new frm.contentWindow.AppMobi.Acceleration(acc.x, acc.y, acc.z, false);
	accelStep++;
	if( accelStep < accelArray.length )
		setTimeout(doAccelStep,accelDelay);
	else
		accelReplayFinish();
}